name: sipayu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  nb_utils: ^6.0.7
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  hooks_riverpod: ^2.4.6
  flutter_hooks: ^0.20.3
  dio: ^5.3.2
  alice: ^0.4.1
  svg_flutter: ^0.0.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  timeline_tile: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/sipayu.png"
  min_sdk_android: 22 # android min sdk min:16, default 21
 

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/dummy_data/

